install: |-
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo apt-get install bsdmainutils
  sudo gem install --no-rdoc --no-ri pdd
architect:
- yegor256
- alex-palevsky
assets:
  id_rsa: yegor256/home#assets/heroku-key
  settings.xml: yegor256/home#assets/dd/settings.xml
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    mvn help:system clean install -Pqulice -Pdd --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
deploy:
  script: |-
    mvn clean package -Pdd --errors --settings ../settings.xml --batch-mode
    mvn clean
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Pdd --errors --batch-mode
    git remote add heroku git@heroku.com:wdd.git
    mkdir -p ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/META-INF/MANIFEST.MF
    sed -i "s/BUILD/${build}/g" src/main/resources/log4j.properties
    git add src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/log4j.properties
    git commit -m 'build number set'
    git add settings.xml
    git commit -m 'settings.xml'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
